import json
import urllib.request

BASE_URL = "http://localhost:3000"
COMPANY_ID = "CO-DDL"

# Controls 41-60 (batches 3 and 4 failed, batch 6 failed)
# Batch 3 = controls[40:60], Batch 4 = controls[60:80], Batch 6 = controls[100:106]

test_controls = [
  {"controlId":"CO-VND-001","processArea":"Vendor and Third-Party Management","processName":"Vendor Due Diligence","description":"Before engaging any new vendor that will host production data or provide core AI capabilities, the operator performs a documented due diligence review covering security posture, data handling, uptime commitments, and pricing terms. The review is recorded in a standardized Vendor Assessment template and must be approved before contracts are signed or services are enabled in production.","controlObjective":"Ensure only appropriately vetted third-party vendors are engaged for critical cloud, AI, and data services.","controlType":"PREVENTIVE","controlNature":"MANUAL","controlFrequency":"AD_HOC","keyControl":True},
  {"controlId":"CO-VND-002","processArea":"Vendor and Third-Party Management","processName":"Vendor Inventory","description":"DDL maintains a governed vendor inventory listing all third parties providing hosting, databases, CI/CD, AI inference, vector storage, and publishing services. Each entry includes service type, data sensitivity, business criticality, contract term, and primary contact. The inventory is reviewed and updated when vendors are added, changed, or terminated.","controlObjective":"Maintain an accurate inventory of critical vendors and their roles in DDL technology stack.","controlType":"DETECTIVE","controlNature":"MANUAL","controlFrequency":"MONTHLY","keyControl":True},
  {"controlId":"CO-VND-003","processArea":"Vendor and Third-Party Management","processName":"Contract and SLA Review","description":"Prior to onboarding or renewing any critical vendor, the operator reviews key terms including uptime SLAs, data breach notification timelines, backup and recovery commitments, data residency, IP ownership, and termination clauses. Deviations from baseline expectations are documented and either accepted with rationale, mitigated, or result in vendor rejection.","controlObjective":"Ensure vendor contracts include appropriate service level, security, and data protection commitments.","controlType":"PREVENTIVE","controlNature":"MANUAL","controlFrequency":"AD_HOC","keyControl":True},
  {"controlId":"CO-VND-004","processArea":"Vendor and Third-Party Management","processName":"Vendor Access Governance","description":"For vendors that provide consoles or admin portals, the operator configures access according to least privilege and disables default or shared accounts. Where supported, SSO, MFA, and role-based access are enabled. Third-party support accounts are activated temporarily with explicit approval and revoked immediately after use.","controlObjective":"Restrict vendor access to only the minimum privileges necessary to support DDL products and infrastructure.","controlType":"PREVENTIVE","controlNature":"MANUAL","controlFrequency":"AD_HOC","keyControl":True},
  {"controlId":"CO-VND-005","processArea":"Vendor and Third-Party Management","processName":"Vendor Incident Monitoring","description":"The operator subscribes to security bulletins, status feeds, and email alerts for core vendors including Vercel, Neon, Cloudflare, and GitHub. Upon receiving a relevant alert, the operator logs the event, evaluates potential impact on DDL systems and data, and documents response actions including temporary mitigations or customer communications.","controlObjective":"Ensure DDL is promptly aware of security advisories and incidents affecting critical vendors.","controlType":"DETECTIVE","controlNature":"MANUAL","controlFrequency":"DAILY","keyControl":True},
  {"controlId":"CO-VND-006","processArea":"Vendor and Third-Party Management","processName":"Vendor Risk Reassessment","description":"On a scheduled basis, the operator revisits vendor risk assessments for key providers to consider changes in DDL reliance, new features in use, or updates to vendor security programs. Any material change in risk results in updated controls, configuration changes, or a documented risk acceptance decision.","controlObjective":"Re-evaluate the risk profile of critical vendors over time to account for changes in usage or vendor posture.","controlType":"DETECTIVE","controlNature":"MANUAL","controlFrequency":"ANNUAL","keyControl":False},
  {"controlId":"CO-VND-007","processArea":"Vendor and Third-Party Management","processName":"Dependency Vulnerability Review","description":"For all production repositories, the operator periodically reviews package manifests and GitHub dependency insights to identify high-severity vulnerabilities or problematic licenses. Identified issues are triaged with upgrades or replacements tracked to completion. Where immediate remediation is not feasible, a risk acceptance note is documented.","controlObjective":"Ensure third-party dependencies in code repositories are governed and do not introduce unmanaged security or licensing risk.","controlType":"DETECTIVE","controlNature":"MANUAL","controlFrequency":"MONTHLY","keyControl":True},
  {"controlId":"CO-VND-008","processArea":"Vendor and Third-Party Management","processName":"Vendor Onboarding Checklist","description":"DDL uses a vendor onboarding checklist that must be completed whenever a new third-party service is adopted. The checklist covers account creation, MFA and access configuration, billing and cost alert setup, log and audit feature enablement, and entry into the vendor inventory.","controlObjective":"Standardize the onboarding of new vendors to ensure required governance, billing, and security steps are completed.","controlType":"PREVENTIVE","controlNature":"MANUAL","controlFrequency":"AD_HOC","keyControl":False},
  {"controlId":"CO-VND-009","processArea":"Vendor and Third-Party Management","processName":"Cloud Cost Monitoring","description":"The operator configures cost and usage dashboards and alerts for vendor platforms where available. At defined intervals, usage and cost metrics are reviewed for unusual spikes, new regions, or atypical workloads. Where anomalies are identified, the operator investigates, documents findings, and adjusts configuration or usage patterns.","controlObjective":"Detect anomalous or unexpected usage patterns that may indicate misconfiguration, abuse, or cost risk across vendor platforms.","controlType":"DETECTIVE","controlNature":"MANUAL","controlFrequency":"MONTHLY","keyControl":False},
  {"controlId":"CO-VND-010","processArea":"Vendor and Third-Party Management","processName":"Vendor Termination Procedure","description":"When discontinuing a vendor, the operator follows a documented offboarding procedure including exporting required data, validating integrity of exports, and issuing deletion or closure requests. The vendor inventory is updated to reflect termination, and any DNS, API keys, or integration configs are removed or rotated to eliminate residual dependency.","controlObjective":"Ensure that when vendor relationships end, DDL data is properly exported, retained, or destroyed in line with governance standards.","controlType":"DETECTIVE","controlNature":"MANUAL","controlFrequency":"AD_HOC","keyControl":True},
  {"controlId":"CO-VND-011","processArea":"Vendor and Third-Party Management","processName":"API Dependency Mapping","description":"For each external API integrated into DDL products, the operator documents the purpose, authentication method, rate limits, and error-handling behavior in a centralized API dependency register. Health checks or synthetic calls are configured where feasible to detect outages or breaking changes before they impact end users.","controlObjective":"Maintain visibility into critical external APIs and manage the operational risk they introduce.","controlType":"DETECTIVE","controlNature":"MANUAL","controlFrequency":"MONTHLY","keyControl":False},
  {"controlId":"CO-VND-012","processArea":"Vendor and Third-Party Management","processName":"Local AI Vendor Governance","description":"Ollama and ChromaDB are treated as vendor components: versions in use are tracked, upgrade notes are documented, and configuration is stored in a governed runbook. Before upgrading models or ChromaDB versions, the operator reviews release notes, tests in a non-production context where possible, and documents rollback steps.","controlObjective":"Govern the use of local AI and vector database components as critical third-party infrastructure within DDL stack.","controlType":"PREVENTIVE","controlNature":"MANUAL","controlFrequency":"AD_HOC","keyControl":True},
  {"controlId":"CO-HR-001","processArea":"HR and Workforce Governance","processName":"Contractor Identity Verification","description":"Prior to provisioning, contractors must submit government ID, proof of eligibility to work, and complete identity verification via an approved vendor. Access provisioning is blocked until signed IP assignment and confidentiality agreements are uploaded and verified.","controlObjective":"Verify contractor identity and legal eligibility before granting any system or data access.","controlType":"PREVENTIVE","controlNature":"MANUAL","controlFrequency":"AD_HOC","keyControl":True},
  {"controlId":"CO-HR-002","processArea":"HR and Workforce Governance","processName":"Role Catalog and Access Mapping","description":"DDL maintains a role catalog that defines responsibilities, required approvals, and the exact access entitlements for each role. HR and IT use the catalog to provision accounts and validate access requests. Any deviation from the catalog requires documented justification and dual approval.","controlObjective":"Ensure every role has a documented set of responsibilities and least-privilege access mappings.","controlType":"PREVENTIVE","controlNature":"MANUAL","controlFrequency":"AD_HOC","keyControl":True},
  {"controlId":"CO-HR-003","processArea":"HR and Workforce Governance","processName":"Access Provisioning SLA","description":"Provisioning occurs within two business days after onboarding verification. Offboarding triggers automated deprovisioning within four hours of termination notification and a manual confirmation step. Exceptions require documented approval and are logged for audit.","controlObjective":"Ensure timely provisioning for onboarding and immediate revocation on termination to prevent orphaned access.","controlType":"PREVENTIVE","controlNature":"MANUAL","controlFrequency":"AD_HOC","keyControl":True},
  {"controlId":"CO-HR-004","processArea":"HR and Workforce Governance","processName":"IP Assignment and Confidentiality","description":"All contractors and employees sign IP assignment and confidentiality agreements prior to receiving access. HR verifies signed documents and blocks access until verification completes. Disputes or missing agreements escalate to legal and are recorded.","controlObjective":"Ensure company ownership of deliverables and protection of confidential information.","controlType":"PREVENTIVE","controlNature":"MANUAL","controlFrequency":"AD_HOC","keyControl":True},
  {"controlId":"CO-HR-005","processArea":"HR and Workforce Governance","processName":"Background Screening","description":"Roles with access to financial systems, governance artifacts, or client data require background checks covering criminal history and employment verification. Results are reviewed by HR and retained per policy. Conditional offers include remediation steps if issues are identified.","controlObjective":"Reduce insider and fraud risk by screening candidates for sensitive positions.","controlType":"PREVENTIVE","controlNature":"MANUAL","controlFrequency":"AD_HOC","keyControl":False},
  {"controlId":"CO-HR-006","processArea":"HR and Workforce Governance","processName":"Access Recertification","description":"Owners recertify access quarterly using an automated report. Unnecessary access is revoked and recertification decisions are logged. Exceptions require justification and are time-boxed.","controlObjective":"Ensure ongoing appropriateness of access rights for all contractors and employees.","controlType":"DETECTIVE","controlNature":"MANUAL","controlFrequency":"QUARTERLY","keyControl":True},
  {"controlId":"CO-HR-007","processArea":"HR and Workforce Governance","processName":"Offboarding Checklist","description":"Offboarding requires completion of a checklist covering account revocation, device return, data transfer, and confirmation of IP assignment. HR verifies checklist completion and records evidence before final settlement. Any outstanding items generate a hold and escalation.","controlObjective":"Ensure all access, credentials, and company assets are recovered and accounts closed on termination.","controlType":"DETECTIVE","controlNature":"MANUAL","controlFrequency":"AD_HOC","keyControl":True},
  {"controlId":"CO-HR-008","processArea":"HR and Workforce Governance","processName":"Standards Training Acknowledgement","description":"New hires and contractors complete onboarding training covering key DDL standards and data handling. Completion and signed acknowledgements are required before access renewal and are stored in HR records. Annual refreshers are enforced.","controlObjective":"Ensure workforce awareness of governance, security, and operational standards.","controlType":"PREVENTIVE","controlNature":"MANUAL","controlFrequency":"ANNUAL","keyControl":False},
]

print(f"Testing {len(test_controls)} controls one at a time...")

for i, ctrl in enumerate(test_controls):
    payload = {"companyId": COMPANY_ID, "controls": [ctrl], "mode": "execute"}
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"{BASE_URL}/api/import",
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST"
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read())
            status = "created" if result["created"] > 0 else "updated"
            print(f"  {i+41} {ctrl['controlId']}: OK ({status})")
    except Exception as e:
        print(f"  {i+41} {ctrl['controlId']}: FAILED - {e}")
