import json
import urllib.request

BASE_URL = "http://localhost:3000"
COMPANY_ID = "CO-DDL"

controls = [
  # ── ITGC — Archer Hawthorne ──────────────────────────────────────────────
  {
    "controlId": "CO-ITGC-001",
    "processArea": "IT General Controls",
    "processName": "Access Management",
    "description": "Access to GitHub repositories is restricted to the operator and approved council seats via GitHub Teams with least-privilege principles. MFA is enforced for all accounts. Access logs are reviewed monthly via GitHub Audit Log.",
    "controlObjective": "Ensure only authorized personnel have access to DDL GitHub repositories to prevent unauthorized changes or data leaks.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-ITGC-002",
    "processArea": "IT General Controls",
    "processName": "Change Management",
    "description": "Deployments to production require automated CI/CD checks via Vercel npm run build and a deployment log recording timestamp, deployer, linked PR, and rollback plan. Emergency deployments require post-hoc council review within 24 hours.",
    "controlObjective": "Ensure all production deployments follow a governed change management process to prevent outages or unauthorized changes.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-ITGC-003",
    "processArea": "IT General Controls",
    "processName": "Backup and Recovery",
    "description": "Neon PostgreSQL databases are configured with automated daily backups with 30-day retention and point-in-time recovery enabled. Manual backup validation is performed weekly by running a test restore to staging.",
    "controlObjective": "Ensure all production databases are backed up and recoverable to prevent data loss.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "WEEKLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-ITGC-004",
    "processArea": "IT General Controls",
    "processName": "Infrastructure Security",
    "description": "Cloudflare WAF rules (OWASP Top 10) and TLS 1.3+ are enforced for all domains. Vercel deployment protection is enabled with environment variables encrypted. Audit logs are reviewed weekly for unauthorized access.",
    "controlObjective": "Ensure Cloudflare and Vercel configurations are secured to prevent unauthorized access or attacks.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-ITGC-005",
    "processArea": "IT General Controls",
    "processName": "Local AI Infrastructure",
    "description": "Ollama model versions are pinned in versioned Modelfiles. ChromaDB undergoes nightly backups via dex-sweep.py and weekly collection integrity checks. Corruption recovery is tested monthly by restoring from backup.",
    "controlObjective": "Ensure local AI infrastructure is secure, version-controlled, and recoverable.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "WEEKLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-ITGC-006",
    "processArea": "IT General Controls",
    "processName": "System Availability",
    "description": "Cloudflare Status Page monitors auditforge.dev and blindspot.bet against 99.9% SLA. Vercel Analytics tracks deployment success rates. Alerts are sent to operator for downtime exceeding 5 minutes. Performance baselines are reviewed quarterly.",
    "controlObjective": "Ensure critical services are monitored for uptime and performance.",
    "controlType": "DETECTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "QUARTERLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-ITGC-007",
    "processArea": "IT General Controls",
    "processName": "Configuration Management",
    "description": "Vercel and Cloudflare configuration files are stored in GitHub with PR approvals required for changes. Environment variables are managed via Vercel CLI and never hardcoded. Prisma schema changes are version-controlled with documented rollback plans.",
    "controlObjective": "Ensure all infrastructure configurations are version-controlled and changes are reviewed.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-ITGC-008",
    "processArea": "IT General Controls",
    "processName": "Secret Management",
    "description": "API keys and secrets are stored in Vercel Environment Variables or GitHub Secrets and never committed to repositories. Neon DB credentials are rotated quarterly. Vercel Audit Log is reviewed monthly for unauthorized key usage.",
    "controlObjective": "Ensure API keys and secrets are securely stored and rotated.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "QUARTERLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-ITGC-009",
    "processArea": "IT General Controls",
    "processName": "Incident Response",
    "description": "Cloudflare WAF alerts detect SQLi/XSS attempts. Vercel deployment failures trigger operator notifications. An incident playbook documents escalation paths and post-incident review requirements within 48 hours via council review.",
    "controlObjective": "Ensure security incidents are detected, logged, and resolved promptly.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-ITGC-010",
    "processArea": "IT General Controls",
    "processName": "Log Retention",
    "description": "GitHub Audit Logs are retained 1 year. Vercel Deployment Logs are retained 6 months. Ollama/ChromaDB logs are retained 3 months. Monthly reviews check GitHub/Vercel logs for anomalies. Weekly reviews check Ollama/ChromaDB for errors.",
    "controlObjective": "Ensure logs for critical systems are retained and reviewed to detect anomalies.",
    "controlType": "DETECTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-ITGC-011",
    "processArea": "IT General Controls",
    "processName": "Dependency Management",
    "description": "New dependencies require council review. Monthly dependency scans are performed via npm audit and safety check. Critical CVE patches are applied within 72 hours. A dependency inventory is maintained in the infrastructure repository.",
    "controlObjective": "Ensure third-party dependencies are vetted and updated to prevent vulnerabilities.",
    "controlType": "DETECTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-ITGC-012",
    "processArea": "IT General Controls",
    "processName": "Disaster Recovery",
    "description": "Nightly ChromaDB backups are performed to the DDL Backup drive. Ollama model snapshots are stored separately. Recovery tests are performed quarterly. GAMINGLAPTOP (RTX 3060) is configured as a hot standby with semi-annual failover testing.",
    "controlObjective": "Ensure Dex Jr. local AI infrastructure can be recovered from catastrophic failures.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "QUARTERLY",
    "keyControl": True,
  },

  # ── GOV — Marcus Caldwell ────────────────────────────────────────────────
  {
    "controlId": "CO-GOV-001",
    "processArea": "Governance and Oversight",
    "processName": "Council Decision Ratification",
    "description": "All significant architectural decisions require a formal council review with independent responses from a minimum of 5 of 9 cloud seats before operator sign-off. The ratification record includes review ID, participating seats, individual verdicts, synthesis findings, and operator decision with date. No related code changes may be deployed until the verdict is recorded.",
    "controlObjective": "Ensure no architectural or product decision is implemented without documented council deliberation and operator ratification.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-GOV-002",
    "processArea": "Governance and Oversight",
    "processName": "Standards Registry",
    "description": "On a quarterly basis, the operator performs a completeness review of the standards registry verifying every active standard has a unique ID and version, no two standards govern the same scope without cross-reference, and every standard marked RATIFIED has a corresponding council review record.",
    "controlObjective": "Ensure the DDL standards registry remains current, complete, and free of orphaned or contradictory entries.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "QUARTERLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-GOV-003",
    "processArea": "Governance and Oversight",
    "processName": "ADR Immutability",
    "description": "Once an ADR receives operator ratification it is locked. Any material change requires a new ADR with explicit supersession language referencing the original by ID. The new ADR must pass council review before the original is marked superseded. Both documents are retained in the Vault.",
    "controlObjective": "Ensure that ratified ADRs cannot be modified without a formal supersession process.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-GOV-004",
    "processArea": "Governance and Oversight",
    "processName": "Audit Trail Integrity",
    "description": "AuditForge middleware enforces Silent Fix Prevention: every mutation to Fact_Control and related tables writes a corresponding record to the AuditTrail table. The trail records entity type, entity ID, field changed, old value, new value, actor, timestamp, and mutation type. The AuditTrail table is append-only enforced at the ORM level.",
    "controlObjective": "Ensure every data mutation in AuditForge is recorded with actor, timestamp, and change description, preventing silent fixes.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "DAILY",
    "keyControl": True,
  },
  {
    "controlId": "CO-GOV-005",
    "processArea": "Governance and Oversight",
    "processName": "Council Participation Monitoring",
    "description": "The operator reviews council participation rates monthly using the Council Vote Ledger. For each seat, the review tracks total reviews distributed, total responses received, refusal count, and response rate. Any seat with a response rate below 60% in a rolling 90-day window is flagged for evaluation.",
    "controlObjective": "Detect persistent non-participation by council seats to ensure deliberation quality.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-GOV-006",
    "processArea": "Governance and Oversight",
    "processName": "OperatorManifest Version Control",
    "description": "Each DDL product maintains its own OperatorManifest (llms.txt). When governance changes occur, all affected manifests must be updated within one build cycle. The operator verifies manifest currency and cross-product consistency. PII hardening requirements are enforced: no employer name, no local paths, no personal milestones in any public manifest.",
    "controlObjective": "Ensure all live OperatorManifest files across DDL products are current, consistent, and reflect ratified governance.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-GOV-007",
    "processArea": "Governance and Oversight",
    "processName": "Single Point of Failure Mitigation",
    "description": "The operator maintains a secure credential registry documenting all service accounts, domain registrations with renewal dates, and database connection strings. Clayton Hotze is designated as emergency access contact with documented instructions for redeploying products, accessing the database, and restoring the corpus. The credential registry is reviewed quarterly.",
    "controlObjective": "Ensure critical DDL systems and credentials are recoverable if the operator is unavailable for an extended period.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "QUARTERLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-GOV-008",
    "processArea": "Governance and Oversight",
    "processName": "Injection Resistance Testing",
    "description": "On a quarterly basis, the operator conducts an injection resistance test across all council seats. A review document containing an embedded canary string is distributed. Models that execute the canary rather than ignoring it are flagged. Results are logged in the Council Vote Ledger with a dedicated injection_resistance score.",
    "controlObjective": "Ensure council models do not execute embedded directives within review documents, preserving governance deliberation integrity.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "QUARTERLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-GOV-009",
    "processArea": "Governance and Oversight",
    "processName": "Vault Intake Governance",
    "description": "Documents entering the Vault must pass through the 00_INTAKE queue and be verified against the STD-VAULT-002 template: correct header block with required metadata fields, correct naming convention, and correct folder assignment by document type. Documents that fail validation remain in 00_INTAKE/archive until corrected.",
    "controlObjective": "Ensure every document entering the DDL Knowledge Vault conforms to template and naming requirements of STD-VAULT-002.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": False,
  },
  {
    "controlId": "CO-GOV-010",
    "processArea": "Governance and Oversight",
    "processName": "Corpus Constitutional Hierarchy",
    "description": "ADR-CORPUS-001 defines five tiers with fixed weights governing retrieval precedence. This control verifies the dex-weights.py configuration matches the ratified ADR weights exactly, the query router routes queries to correct collections, and the dex_dave isolation rule is enforced. Verification is performed after any change to weights or the collection registry.",
    "controlObjective": "Ensure the collection authority model is correctly implemented in retrieval code and no collection outranks its designated tier.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-GOV-011",
    "processArea": "Governance and Oversight",
    "processName": "DCR Sequencing Completeness",
    "description": "Every council review receives a sequential DCR number at distribution. The DCR registry maintains review topic, date, seats that responded, individual verdicts, synthesis status, and operator disposition. No DCR number may be reused or skipped without documentation. The registry is reconciled against the Council Vote Ledger quarterly.",
    "controlObjective": "Ensure the DDL Council Review numbering sequence is complete, unambiguous, and traceable.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "QUARTERLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-GOV-012",
    "processArea": "Governance and Oversight",
    "processName": "Architectural Boundary Enforcement",
    "description": "AuditForge's architectural boundary is ratified and immovable: the product defines what controls are, it does not test if they work; it generates governed documentation, it does not issue opinions. No AuditForge function may render a pass/fail judgment, store evidence files, or contain an audit opinion. Verified during council review of any AuditForge feature and during code review before deployment.",
    "controlObjective": "Prevent AuditForge from crossing the ratified architectural boundary between a System of Structure and a System of Execution.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },

  # ── FIN — Elias Mercer ───────────────────────────────────────────────────
  {
    "controlId": "CO-FIN-001",
    "processArea": "Financial Reporting and Revenue",
    "processName": "Revenue Recognition",
    "description": "All SaaS subscriptions are reviewed monthly against contract terms. Revenue is recognized ratably over the subscription period once access is granted. Deferred revenue liability is calculated via Prisma queries and reconciled to the general ledger. Manual overrides require dual approval with documented rationale.",
    "controlObjective": "Ensure subscription revenue is recognized only when performance obligations are satisfied per ASC 606.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-FIN-002",
    "processArea": "Financial Reporting and Revenue",
    "processName": "Invoicing Controls",
    "description": "Invoices are generated from Prisma queries against active subscriptions and consulting agreements. Every invoice is reviewed by the operator before sending. A digital approval record is logged in ControlStatusLog. Changes to billing rates or terms require a signed amendment uploaded to the evidence vault.",
    "controlObjective": "Ensure all customer invoices are accurate, complete, and authorized before issuance.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-FIN-003",
    "processArea": "Financial Reporting and Revenue",
    "processName": "Bank Reconciliation",
    "description": "Monthly bank statements are downloaded and reconciled to the Neon ledger within 5 business days of month-end. Outstanding items are investigated and cleared. Subscription and consulting receipts are matched to invoice records. Cut-off procedures ensure no post-period receipts are recorded in the prior month.",
    "controlObjective": "Ensure all cash receipts and disbursements are recorded in the correct period and reconciled to bank statements.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-FIN-004",
    "processArea": "Financial Reporting and Revenue",
    "processName": "Deferred Revenue Roll-Forward",
    "description": "Deferred revenue is calculated daily via a scheduled Prisma query that prorates active subscriptions. A monthly roll-forward report compares beginning balance plus new billings minus recognized revenue equals ending balance. Variances greater than 5% trigger review. The report is attached to the financial close package.",
    "controlObjective": "Accurately calculate and track deferred revenue to ensure proper recognition timing.",
    "controlType": "DETECTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-FIN-005",
    "processArea": "Financial Reporting and Revenue",
    "processName": "Consulting Revenue Contract Review",
    "description": "Every consulting contract is reviewed and stored in the evidence vault before work begins. Revenue is recognized only when milestones are approved in ControlStatusLog. Partial billings are tracked separately from fixed-fee arrangements. Unbilled revenue is reviewed monthly for collectibility.",
    "controlObjective": "Ensure all consulting engagements have signed agreements and revenue is recognized only upon milestone completion.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-FIN-006",
    "processArea": "Financial Reporting and Revenue",
    "processName": "Month-End Close Checklist",
    "description": "A standardized month-end close checklist is maintained covering reconciliations, revenue recognition, deferred calculation, and variance review. Each step is signed off with date and reviewer. The checklist is attached to the final close package and logged in AuditTrail.",
    "controlObjective": "Ensure all financial close procedures are completed and approved before reporting.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-FIN-007",
    "processArea": "Financial Reporting and Revenue",
    "processName": "Subscription Cancellation Processing",
    "description": "Cancellation requests are logged in a dedicated input table. Refunds are calculated pro-rata and processed through the payment processor. The transaction is recorded in the ledger with a corresponding debit to revenue. All cancellations require operator approval before processing.",
    "controlObjective": "Ensure cancellations and refunds are processed accurately and timely to prevent revenue leakage.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": False,
  },
  {
    "controlId": "CO-FIN-008",
    "processArea": "Financial Reporting and Revenue",
    "processName": "Related Party Transaction Review",
    "description": "Monthly review of all transactions for related-party indicators including same operator, council members, or known affiliates. Any identified transactions are documented in a Related-Party Log with nature, amount, and approval. Disclosure is prepared for financial statements.",
    "controlObjective": "Identify and properly disclose any related-party transactions.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-FIN-009",
    "processArea": "Financial Reporting and Revenue",
    "processName": "Revenue Cut-Off Testing",
    "description": "At month-end, a sample of subscriptions and consulting invoices is tested for proper cut-off. Subscriptions crossing month-end are prorated. Consulting milestones completed after period-end are deferred. Results are documented and variances investigated.",
    "controlObjective": "Ensure revenue is recorded in the correct accounting period.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-FIN-010",
    "processArea": "Financial Reporting and Revenue",
    "processName": "Financial Statement Review",
    "description": "Draft financial statements are prepared from Neon queries and reviewed by the operator against source reconciliations. Key metrics including revenue, deferred revenue, and cash are footed to supporting reports. Approval is documented in AuditTrail before any external distribution.",
    "controlObjective": "Ensure financial statements are reviewed for accuracy before external use.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-FIN-011",
    "processArea": "Financial Reporting and Revenue",
    "processName": "Churn and Renewal Tracking",
    "description": "A monthly churn report is generated from active versus cancelled subscriptions. Renewal rates are calculated by cohort. Churn reasons are logged in a dedicated field. Trends are reviewed against prior periods and flagged if greater than 5% variance.",
    "controlObjective": "Monitor renewal rates and churn to support accurate revenue forecasting.",
    "controlType": "DETECTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "MONTHLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-FIN-012",
    "processArea": "Financial Reporting and Revenue",
    "processName": "Consulting Milestone Validation",
    "description": "Milestones are tracked with evidence upload requirement. Revenue is recognized only after operator approval in ControlStatusLog. Uncompleted milestones remain in deferred revenue until validated.",
    "controlObjective": "Ensure consulting revenue is recognized only upon verified milestone completion.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },

  # ── VND — Max Sullivan ───────────────────────────────────────────────────
  {
    "controlId": "CO-VND-001",
    "processArea": "Vendor and Third-Party Management",
    "processName": "Vendor Due Diligence",
    "description": "Before engaging any new vendor that will host production data or provide core AI capabilities, the operator performs a documented due diligence review covering security posture, data handling, uptime commitments, and pricing terms. The review is recorded in a standardized Vendor Assessment template and must be approved before contracts are signed or services are enabled in production.",
    "controlObjective": "Ensure only appropriately vetted third-party vendors are engaged for critical cloud, AI, and data services.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-VND-002",
    "processArea": "Vendor and Third-Party Management",
    "processName": "Vendor Inventory",
    "description": "DDL maintains a governed vendor inventory listing all third parties providing hosting, databases, CI/CD, AI inference, vector storage, and publishing services. Each entry includes service type, data sensitivity, business criticality, contract term, and primary contact. The inventory is reviewed and updated when vendors are added, changed, or terminated.",
    "controlObjective": "Maintain an accurate inventory of critical vendors and their roles in DDL's technology stack.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-VND-003",
    "processArea": "Vendor and Third-Party Management",
    "processName": "Contract and SLA Review",
    "description": "Prior to onboarding or renewing any critical vendor, the operator reviews key terms including uptime SLAs, data breach notification timelines, backup and recovery commitments, data residency, IP ownership, and termination clauses. Deviations from baseline expectations are documented and either accepted with rationale, mitigated via configuration, or result in vendor rejection.",
    "controlObjective": "Ensure vendor contracts include appropriate service level, security, and data protection commitments aligned with DDL's risk appetite.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-VND-004",
    "processArea": "Vendor and Third-Party Management",
    "processName": "Vendor Access Governance",
    "description": "For vendors that provide consoles or admin portals, the operator configures access according to least privilege and disables default or shared accounts. Where supported, SSO, MFA, and role-based access are enabled. Third-party support accounts are either not granted persistent access or are activated temporarily with explicit approval and revoked immediately after use.",
    "controlObjective": "Restrict vendor access to only the minimum privileges necessary to support DDL's products and infrastructure.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-VND-005",
    "processArea": "Vendor and Third-Party Management",
    "processName": "Vendor Incident Monitoring",
    "description": "The operator subscribes to security bulletins, status feeds, and email alerts for core vendors including Vercel, Neon, Cloudflare, and GitHub. Upon receiving a relevant alert, the operator logs the event, evaluates potential impact on DDL systems and data, and documents response actions including temporary mitigations or customer communications.",
    "controlObjective": "Ensure DDL is promptly aware of security advisories and incidents affecting critical vendors.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "DAILY",
    "keyControl": True,
  },
  {
    "controlId": "CO-VND-006",
    "processArea": "Vendor and Third-Party Management",
    "processName": "Vendor Risk Reassessment",
    "description": "On a scheduled basis, the operator revisits vendor risk assessments for key providers to consider changes in DDL's reliance, new features in use, or updates to vendor security programs. Any material change in risk results in updated controls, configuration changes, or a documented risk acceptance decision.",
    "controlObjective": "Re-evaluate the risk profile of critical vendors over time to account for changes in usage, data sensitivity, or vendor posture.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "ANNUAL",
    "keyControl": False,
  },
  {
    "controlId": "CO-VND-007",
    "processArea": "Vendor and Third-Party Management",
    "processName": "Dependency Vulnerability Review",
    "description": "For all production repositories, the operator periodically reviews package manifests and GitHub dependency insights to identify high-severity vulnerabilities or problematic licenses. Identified issues are triaged with upgrades or replacements tracked to completion. Where immediate remediation is not feasible, a risk acceptance note is documented.",
    "controlObjective": "Ensure third-party dependencies in code repositories are governed and do not introduce unmanaged security or licensing risk.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-VND-008",
    "processArea": "Vendor and Third-Party Management",
    "processName": "Vendor Onboarding Checklist",
    "description": "DDL uses a vendor onboarding checklist that must be completed whenever a new third-party service is adopted. The checklist covers account creation, MFA and access configuration, billing and cost alert setup, log and audit feature enablement, and entry into the vendor inventory. The checklist must be marked complete and stored with the vendor record.",
    "controlObjective": "Standardize the onboarding of new vendors to ensure required governance, billing, and security steps are completed.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": False,
  },
  {
    "controlId": "CO-VND-009",
    "processArea": "Vendor and Third-Party Management",
    "processName": "Cloud Cost Monitoring",
    "description": "The operator configures cost and usage dashboards and alerts for vendor platforms where available. At defined intervals, usage and cost metrics are reviewed for unusual spikes, new regions, or atypical workloads. Where anomalies are identified, the operator investigates, documents findings, and adjusts configuration or usage patterns.",
    "controlObjective": "Detect anomalous or unexpected usage patterns that may indicate misconfiguration, abuse, or cost risk across vendor platforms.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-VND-010",
    "processArea": "Vendor and Third-Party Management",
    "processName": "Vendor Termination Procedure",
    "description": "When discontinuing a vendor, the operator follows a documented offboarding procedure including exporting required data, validating integrity of exports, and issuing deletion or closure requests. The vendor inventory is updated to reflect termination, and any DNS, API keys, or integration configs are removed or rotated to eliminate residual dependency.",
    "controlObjective": "Ensure that when vendor relationships end, DDL data is properly exported, retained, or destroyed in line with governance standards.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-VND-011",
    "processArea": "Vendor and Third-Party Management",
    "processName": "API Dependency Mapping",
    "description": "For each external API integrated into DDL products, the operator documents the purpose, authentication method, rate limits, and error-handling behavior in a centralized API dependency register. Health checks or synthetic calls are configured where feasible to detect outages or breaking changes before they impact end users.",
    "controlObjective": "Maintain visibility into critical external APIs and manage the operational risk they introduce.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-VND-012",
    "processArea": "Vendor and Third-Party Management",
    "processName": "Local AI Vendor Governance",
    "description": "Ollama and ChromaDB are treated as vendor components: versions in use are tracked, upgrade notes are documented, and configuration is stored in a governed runbook. Before upgrading models or ChromaDB versions, the operator reviews release notes, tests in a non-production context where possible, and documents rollback steps.",
    "controlObjective": "Govern the use of local AI and vector database components as critical third-party infrastructure within DDL's stack.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },

  # ── HR — Rowan Bennett ───────────────────────────────────────────────────
  {
    "controlId": "CO-HR-001",
    "processArea": "HR and Workforce Governance",
    "processName": "Contractor Identity Verification",
    "description": "Prior to provisioning, contractors must submit government ID, proof of eligibility to work, and complete identity verification via an approved vendor. Access provisioning is blocked until signed IP assignment and confidentiality agreements are uploaded and verified. Verification records are retained per retention policy.",
    "controlObjective": "Verify contractor identity and legal eligibility before granting any system or data access.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-HR-002",
    "processArea": "HR and Workforce Governance",
    "processName": "Role Catalog and Access Mapping",
    "description": "DDL maintains a role catalog that defines responsibilities, required approvals, and the exact access entitlements for each role. HR and IT use the catalog to provision accounts and validate access requests. Any deviation from the catalog requires documented justification and dual approval.",
    "controlObjective": "Ensure every role has a documented set of responsibilities and least-privilege access mappings.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-HR-003",
    "processArea": "HR and Workforce Governance",
    "processName": "Access Provisioning SLA",
    "description": "Provisioning occurs within two business days after onboarding verification. Offboarding triggers automated deprovisioning within four hours of termination notification and a manual confirmation step. Exceptions require documented approval and are logged for audit.",
    "controlObjective": "Ensure timely provisioning for onboarding and immediate revocation on termination to prevent orphaned access.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-HR-004",
    "processArea": "HR and Workforce Governance",
    "processName": "IP Assignment and Confidentiality",
    "description": "All contractors and employees sign IP assignment and confidentiality agreements prior to receiving access. HR verifies signed documents and blocks access until verification completes. Disputes or missing agreements escalate to legal and are recorded.",
    "controlObjective": "Ensure company ownership of deliverables and protection of confidential information.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-HR-005",
    "processArea": "HR and Workforce Governance",
    "processName": "Background Screening",
    "description": "Roles with access to financial systems, governance artifacts, or client data require background checks covering criminal history and employment verification. Results are reviewed by HR and retained per policy. Conditional offers include remediation steps if issues are identified.",
    "controlObjective": "Reduce insider and fraud risk by screening candidates for sensitive positions.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": False,
  },
  {
    "controlId": "CO-HR-006",
    "processArea": "HR and Workforce Governance",
    "processName": "Access Recertification",
    "description": "Owners recertify access quarterly using an automated report. Unnecessary access is revoked and recertification decisions are logged. Exceptions require justification and are time-boxed.",
    "controlObjective": "Ensure ongoing appropriateness of access rights for all contractors and employees.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "QUARTERLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-HR-007",
    "processArea": "HR and Workforce Governance",
    "processName": "Offboarding Checklist",
    "description": "Offboarding requires completion of a checklist covering account revocation, device return, data transfer, and confirmation of IP assignment. HR verifies checklist completion and records evidence before final settlement. Any outstanding items generate a hold and escalation.",
    "controlObjective": "Ensure all access, credentials, and company assets are recovered and accounts closed on termination.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-HR-008",
    "processArea": "HR and Workforce Governance",
    "processName": "Standards Training Acknowledgement",
    "description": "New hires and contractors complete onboarding training covering key DDL standards and data handling. Completion and signed acknowledgements are required before access renewal and are stored in HR records. Annual refreshers are enforced.",
    "controlObjective": "Ensure workforce awareness of governance, security, and operational standards.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "ANNUAL",
    "keyControl": False,
  },
  {
    "controlId": "CO-HR-009",
    "processArea": "HR and Workforce Governance",
    "processName": "Contractor Classification Review",
    "description": "HR reviews contractor engagements quarterly to confirm classification criteria covering control, independence, and deliverables, and updates contracts where necessary. Misclassifications trigger remediation and legal review. Documentation of classification rationale is retained.",
    "controlObjective": "Ensure correct worker classification and contractual terms to mitigate legal and tax risk.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "QUARTERLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-HR-010",
    "processArea": "HR and Workforce Governance",
    "processName": "Deliverable Acceptance Controls",
    "description": "Deliverables are accepted against predefined criteria and test evidence. Acceptance requires sign-off from the owner and is recorded in the engagement file. Non-conforming work triggers remediation plans and may affect future engagement terms.",
    "controlObjective": "Ensure contractor deliverables meet acceptance criteria before payment or continued engagement.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-HR-011",
    "processArea": "HR and Workforce Governance",
    "processName": "Sensitive Data Access Minimization",
    "description": "HR coordinates with data owners to label roles requiring access to sensitive collections. Access is granted only after training and justification, and periodic audits verify minimization. Any access to sensitive data requires a signed NDA and documented business purpose.",
    "controlObjective": "Limit exposure of sensitive information to only those with a business need.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "QUARTERLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-HR-012",
    "processArea": "HR and Workforce Governance",
    "processName": "Workforce Continuity Planning",
    "description": "For critical operator and governance roles, DDL maintains succession plans, cross-training schedules, and documented runbooks. Plans are reviewed semi-annually and tested via role-swap exercises. Gaps trigger hiring or training actions with timelines.",
    "controlObjective": "Reduce single-person dependency and ensure continuity for critical roles.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "ANNUAL",
    "keyControl": True,
  },

  # ── COMM — Ava Sinclair ──────────────────────────────────────────────────
  {
    "controlId": "CO-COMM-001",
    "processArea": "Communications and Ethics",
    "processName": "Publication Governance",
    "description": "Prior to publication on Substack, every CanonPress article draft is subjected to a final review by the operator. This review verifies factual accuracy, checks for disclosures of sensitive operational details, and ensures the tone and quality meet established standards. A log of approved articles is maintained linking the final draft to the published URL.",
    "controlObjective": "Ensure all published articles align with DDL's brand voice, values, and do not disclose confidential or inaccurate information.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-COMM-002",
    "processArea": "Communications and Ethics",
    "processName": "Product Launch Messaging Control",
    "description": "For any new product launch, a formal Communications Plan is drafted covering key messaging, feature descriptions, and pricing. The plan is reviewed and approved by the operator before public release. The approval signifies that all public statements are factually correct and strategically aligned with the product's vision.",
    "controlObjective": "Ensure messaging for new product launches is accurate, consistent, and approved prior to public release.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-COMM-003",
    "processArea": "Communications and Ethics",
    "processName": "Council Deliberation Redaction",
    "description": "Before any AutoCouncil deliberation transcript is published or ingested into a public-facing corpus, it undergoes a manual redaction process. The operator reviews the transcript to identify and remove API keys, unannounced product details, or sensitive internal metrics. The redacted version is saved as a distinct artifact for publication.",
    "controlObjective": "Prevent inadvertent disclosure of sensitive operational or strategic information contained within AI council deliberations.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-COMM-004",
    "processArea": "Communications and Ethics",
    "processName": "Brand Asset Governance",
    "description": "DDL maintains a central Brand Governance standard defining approved logos, color palettes, typography, and brand voice. On a quarterly basis, all primary public sites are reviewed against this standard. Deviations are documented and corrected in the next release cycle.",
    "controlObjective": "Maintain a consistent and high-quality brand identity across all external-facing digital properties.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "QUARTERLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-COMM-005",
    "processArea": "Communications and Ethics",
    "processName": "Material Event Disclosure",
    "description": "DDL maintains a formal Incident Communication Protocol. Upon identification of a material event such as a security breach or significant outage, the protocol is activated outlining steps for internal assessment, stakeholder identification, and drafting of a public statement reviewed for clarity and accuracy before publication.",
    "controlObjective": "Ensure timely and accurate disclosure of material events.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-COMM-006",
    "processArea": "Communications and Ethics",
    "processName": "Conflict of Interest Declaration",
    "description": "On an annual basis, the operator completes a Conflict of Interest disclosure form documenting any external relationships, investments, or business interests that could conflict with DDL's operations or client engagements. The completed form is signed, dated, and archived as a formal governance record.",
    "controlObjective": "Identify and mitigate potential conflicts of interest that could compromise the operator's or DDL's objectivity.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "ANNUAL",
    "keyControl": True,
  },
  {
    "controlId": "CO-COMM-007",
    "processArea": "Communications and Ethics",
    "processName": "Website Content Change Review",
    "description": "All substantive changes to content on DDL's primary web properties are managed via GitHub pull requests. The operator reviews each pull request before merging to the main branch which triggers automated Vercel deployment. This review serves as an approval gate ensuring content is accurate and brand-aligned before going live.",
    "controlObjective": "Prevent unauthorized or inaccurate changes from being published to DDL's primary web properties.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-COMM-008",
    "processArea": "Communications and Ethics",
    "processName": "Social Media Monitoring",
    "description": "Official DDL social media accounts are reviewed on a weekly basis by the operator. The review checks for comments or posts that may require a response, correction, or removal in accordance with DDL's public communication policy. Any significant issues identified are logged and addressed.",
    "controlObjective": "Detect and respond to inappropriate, inaccurate, or off-brand communications posted on official DDL social media accounts.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "WEEKLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-COMM-009",
    "processArea": "Communications and Ethics",
    "processName": "External Stakeholder Inquiry Management",
    "description": "DDL maintains a central point of contact for all external inquiries. A log is maintained of all substantive inquiries recording the date, inquiring party, nature of the request, and the response provided. This ensures a complete record of external communications and allows for consistent messaging.",
    "controlObjective": "Ensure that inquiries from external stakeholders are handled in a consistent, professional, and timely manner.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": False,
  },
  {
    "controlId": "CO-COMM-010",
    "processArea": "Communications and Ethics",
    "processName": "Testimonial and Case Study Verification",
    "description": "Before any client testimonial or case study is published, a written confirmation is obtained from the client explicitly granting DDL permission to use their name, statements, and results publicly. The approval record is archived and linked to the published material.",
    "controlObjective": "Ensure all client testimonials or case studies are authentic, accurate, and approved for public use.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": False,
  },
  {
    "controlId": "CO-COMM-011",
    "processArea": "Communications and Ethics",
    "processName": "Open Source Release Policy",
    "description": "DDL follows a documented policy for all open-source activities. Before a DDL project is made public on GitHub, its license is formally selected and documented. Contributions to external projects are reviewed to ensure they do not expose proprietary DDL code or trade secrets.",
    "controlObjective": "Govern the release of DDL intellectual property as open source and contributions to third-party projects.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": False,
  },

  # ── OCM — Leo Prescott ───────────────────────────────────────────────────
  {
    "controlId": "CO-OCM-001",
    "processArea": "Operations and Change Management",
    "processName": "Branch Protection",
    "description": "The operator utilizes GitHub for all source code version control. The main branch is protected as the source of truth for production code. Direct deployments to web properties are executed strictly from this repository. Branch protection rules prevent direct commits to main.",
    "controlObjective": "Prevent unauthorized or unreviewed code from entering the production deployment pipeline.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "DAILY",
    "keyControl": True,
  },
  {
    "controlId": "CO-OCM-002",
    "processArea": "Operations and Change Management",
    "processName": "Deployment Standardization",
    "description": "All scripted local deployments, file operations, or codebase pushes utilize standardized PowerShell scripts adhering to STD-PS-001. Scripts enforce strict pre-flight checks, require git status verification before staging, and validate exact file counts before executing pushes to remote repositories.",
    "controlObjective": "Ensure all manual deployments or file transfers are executed accurately and prevent silent failures.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": False,
  },
  {
    "controlId": "CO-OCM-003",
    "processArea": "Operations and Change Management",
    "processName": "Database Migration Governance",
    "description": "All database schema modifications for Neon PostgreSQL instances are executed strictly via Prisma migrations. Schema changes are evaluated locally against a development database before being applied to the production Neon environment, ensuring complete synchronization between the application ORM and database state.",
    "controlObjective": "Prevent destructive database schema changes and ensure database structure aligns with application code.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-OCM-004",
    "processArea": "Operations and Change Management",
    "processName": "Environment Variable Management",
    "description": "Production environment variables are stored securely within the Vercel project settings and Cloudflare configuration dashboards. Secrets are never hardcoded into GitHub repositories, and access to administrative consoles requires authenticated operator access.",
    "controlObjective": "Protect sensitive API keys, database URLs, and configuration secrets from exposure.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "DAILY",
    "keyControl": True,
  },
  {
    "controlId": "CO-OCM-005",
    "processArea": "Operations and Change Management",
    "processName": "AI Modelfile Versioning",
    "description": "Updates to the local AI model are governed by explicitly versioned Modelfiles. Changes to system prompts, context windows, or model weights are tested in isolation, ratified via council review, and explicitly documented in the changelog before overriding the active Ollama model instance on the local rig.",
    "controlObjective": "Ensure local AI inference operates on approved, tested, and governed parameters.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-OCM-006",
    "processArea": "Operations and Change Management",
    "processName": "Automated Deployment and Rollback",
    "description": "Production deployments for web properties are triggered automatically via Vercel GitHub integration upon commits to the main branch. Vercel maintains immutable build snapshots allowing instantaneous one-click rollbacks if a newly deployed version introduces critical operational errors.",
    "controlObjective": "Ensure deployments are consistent, automated, and rollbacks are immediately available.",
    "controlType": "DETECTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "DAILY",
    "keyControl": True,
  },
  {
    "controlId": "CO-OCM-007",
    "processArea": "Operations and Change Management",
    "processName": "Incident and Friction Logging",
    "description": "Production incidents, Vercel build failures, or severe AI hallucination events are documented by the operator as Friction Logs or mapped directly into Architecture Decision Records. These artifacts are ingested into the DDL Knowledge Vault to build institutional memory and prevent recurrent failures.",
    "controlObjective": "Ensure production incidents and operational friction points are documented and resolved structurally.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": False,
  },
  {
    "controlId": "CO-OCM-008",
    "processArea": "Operations and Change Management",
    "processName": "Resource Monitoring",
    "description": "The operator utilizes native diagnostic tools including WizTree for disk space, Task Manager and Nvidia-SMI for VRAM, and the Neon dashboard for Postgres compute to monitor resource consumption. VRAM exhaustion during heavy AutoCouncil runs or approaching vector database storage limits trigger manual process termination or offloading to the overflow node.",
    "controlObjective": "Detect infrastructure capacity limits before they cause system downtime or data truncation.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "DAILY",
    "keyControl": False,
  },
  {
    "controlId": "CO-OCM-009",
    "processArea": "Operations and Change Management",
    "processName": "Architecture Decision Records",
    "description": "Major architectural changes require a formal ADR documenting the technical problem, the decision, and the rationale. The ADR must be ratified by the AI Council before execution in the production environment. Ratified ADRs are stored in the Vault and are immutable.",
    "controlObjective": "Ensure significant structural changes to the IT environment are evaluated, approved, and preserved.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-OCM-010",
    "processArea": "Operations and Change Management",
    "processName": "Zero-Trust Network Access",
    "description": "Remote communication between the operator's devices is routed exclusively through a private Tailscale WireGuard mesh network. No router ports are forwarded to the public internet for local AI access, database maintenance interfaces, or SSH connections.",
    "controlObjective": "Secure remote access to local infrastructure nodes and prevent unauthorized network intrusion.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "DAILY",
    "keyControl": True,
  },
  {
    "controlId": "CO-OCM-011",
    "processArea": "Operations and Change Management",
    "processName": "Database and Corpus Backup",
    "description": "Neon PostgreSQL databases utilize continuous automated cloud backups with point-in-time recovery capabilities. The local ChromaDB vector corpus is periodically mirrored to a secondary drive using governed PowerShell scripts to protect against physical drive failure on the primary rig.",
    "controlObjective": "Ensure business-critical data can be restored in the event of corruption or catastrophic hardware failure.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "DAILY",
    "keyControl": True,
  },

  # ── RI — Marcus Grey ─────────────────────────────────────────────────────
  {
    "controlId": "CO-RI-001",
    "processArea": "Revenue Integrity and Commissions",
    "processName": "Commission Plan Approval",
    "description": "DDL maintains a governed commission plan record for each active compensation arrangement including effective dates, rate logic, eligible revenue types, exception rules, and approval status. New plans and plan changes must be reviewed and approved by the operator before use, assigned a version identifier, and retained as superseding records rather than overwritten.",
    "controlObjective": "Ensure commission calculations are based on formally approved compensation terms and prevent unauthorized plan changes from affecting payments.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-RI-002",
    "processArea": "Revenue Integrity and Commissions",
    "processName": "Revenue Eligibility Classification",
    "description": "Revenue transactions are classified by type before commission processing to determine whether they are commissionable under the approved plan. The classification logic distinguishes recurring SaaS subscriptions, consulting revenue, adjustments, credits, refunds, and non-commissionable items. Transactions that fail classification rules are flagged for review before entering the payable population.",
    "controlObjective": "Ensure only eligible revenue is included in commission calculations and excluded items are consistently filtered.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-RI-003",
    "processArea": "Revenue Integrity and Commissions",
    "processName": "Source-to-Commission Reconciliation",
    "description": "Before commissions are calculated, the commission input population is reconciled to the underlying source records from the governing billing or revenue dataset for the period. Record counts, total revenue, excluded adjustments, and included commissionable balances are compared to confirm completeness. Any mismatch above defined tolerance must be investigated and resolved before payment is approved.",
    "controlObjective": "Ensure the population used for commission calculations is complete and accurately reconciled to source revenue records.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-RI-004",
    "processArea": "Revenue Integrity and Commissions",
    "processName": "Commission Formula Integrity",
    "description": "Commission calculations are executed through a governed calculation model applying approved plan logic to each eligible transaction. A secondary integrity check verifies sample outputs against independently recomputed results for rate, tier, cap, and threshold logic before final payout is released. Any formula change requires retesting and approval prior to production use.",
    "controlObjective": "Ensure commission calculations apply the correct rates, tiers, caps, and exception logic for each transaction.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-RI-005",
    "processArea": "Revenue Integrity and Commissions",
    "processName": "Period Cutoff Control",
    "description": "Commission processing applies controlled period filters to include only revenue earned within the approved commission window and subject to the applicable plan version in effect at that time. Late entries, backdated changes, refunds, and period-end adjustments are reviewed against cutoff rules to determine whether they belong in the current or subsequent cycle.",
    "controlObjective": "Ensure commissions are calculated using the correct earning period and plan effective dates.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-RI-006",
    "processArea": "Revenue Integrity and Commissions",
    "processName": "Manual Override Approval",
    "description": "Any manual override to calculated commission amounts, revenue eligibility, dispute outcomes, or exception handling must be documented with rationale, linked to the underlying record, and approved before payment processing. Overrides are tracked separately from base calculations so the original calculated result remains visible for audit purposes.",
    "controlObjective": "Prevent unauthorized or unsupported manual adjustments to commission results.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-RI-007",
    "processArea": "Revenue Integrity and Commissions",
    "processName": "Payout Approval Workflow",
    "description": "Commission statements or payout schedules progress through defined statuses including Draft, Review, Approved, and Paid, with release to payment permitted only after required reviews are completed. The workflow requires confirmation that plan version, revenue population, formula results, reconciliation, and overrides have all been reviewed.",
    "controlObjective": "Ensure commission payouts move through a controlled review and approval workflow before release.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-RI-008",
    "processArea": "Revenue Integrity and Commissions",
    "processName": "Commission Statement Accuracy",
    "description": "Before distribution, commission statements are reviewed to confirm that recipient identity, period, relevant transactions, rates, adjustments, and final payable amount match the approved calculation record. Statement generation must pull from the approved data source rather than manually rekeyed values.",
    "controlObjective": "Ensure recipient-facing commission statements accurately reflect approved calculations and supporting detail.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-RI-009",
    "processArea": "Revenue Integrity and Commissions",
    "processName": "Payment File Disbursement Match",
    "description": "The final approved commission payout file is reconciled to the actual payment instruction or disbursement report to confirm that each approved recipient was paid the correct amount once and only once. Differences between approved payout totals and processed payments are investigated before the cycle is closed.",
    "controlObjective": "Ensure approved commission amounts are paid accurately and completely through the disbursement process.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-RI-010",
    "processArea": "Revenue Integrity and Commissions",
    "processName": "Dispute Resolution Log",
    "description": "DDL maintains a dispute log for commission questions, corrections, and appeals including the affected record, issue description, supporting evidence, disposition, and final resolution date. Disputes are evaluated against the approved plan, source revenue records, and prior calculation outputs. Trend review is performed periodically to identify recurring plan ambiguity or control weaknesses.",
    "controlObjective": "Ensure commission disputes are resolved consistently, transparently, and with retained supporting rationale.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": False,
  },
  {
    "controlId": "CO-RI-011",
    "processArea": "Revenue Integrity and Commissions",
    "processName": "Commission Logic Access Control",
    "description": "Access to commission calculation workbooks, scripts, parameter tables, and payout outputs is restricted to the operator and explicitly authorized reviewers based on role and need. Write access to logic and payout artifacts is segregated from view-only access where feasible. Access changes are reviewed when roles or responsibilities change.",
    "controlObjective": "Restrict the ability to modify commission plans, formulas, and payout outputs to authorized personnel only.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "QUARTERLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-RI-012",
    "processArea": "Revenue Integrity and Commissions",
    "processName": "Commission Trend Analytics Review",
    "description": "After each commission cycle, DDL reviews summarized payout analytics by period, revenue type, recipient, and exception category to identify outliers or shifts inconsistent with business activity. The review considers unusual payout spikes, elevated override volume, dispute frequency, and unexpected changes in effective commission rate.",
    "controlObjective": "Detect anomalous payout trends, unusual concentration, or unexpected shifts that may indicate errors or emerging risk.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "MONTHLY",
    "keyControl": False,
  },

  # ── DAI — Kai Langford ───────────────────────────────────────────────────
  {
    "controlId": "CO-DAI-001",
    "processArea": "Data Governance and AI Integrity",
    "processName": "Data Classification",
    "description": "The Data Governance Standard defines data classification levels: Public, Internal, Confidential, Restricted. All ingestion scripts require a classification flag. Files without explicit classification are quarantined and not processed. The classification is stored in ChromaDB metadata and enforced at retrieval time via the query router.",
    "controlObjective": "Ensure all data ingested into the corpus is classified according to sensitivity and handled with appropriate access controls.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "DAILY",
    "keyControl": True,
  },
  {
    "controlId": "CO-DAI-002",
    "processArea": "Data Governance and AI Integrity",
    "processName": "RAG Corpus Integrity Check",
    "description": "A nightly integrity daemon compares a random sample of 100 chunks against their source files. It verifies chunk text still matches the source and that embedding distance is within expected thresholds. Discrepancies trigger an alert to the operator and quarantine of affected chunks.",
    "controlObjective": "Verify that vector embeddings remain synchronized with source documents and that no corruption has occurred.",
    "controlType": "DETECTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "DAILY",
    "keyControl": True,
  },
  {
    "controlId": "CO-DAI-003",
    "processArea": "Data Governance and AI Integrity",
    "processName": "Model Version Control",
    "description": "All Dex Jr. Modelfile versions are stored in GitHub under /modelfiles/ with a corresponding ADR documenting changes. Production deployment requires a council vote LOCK and operator approval. The active Modelfile is symlinked from /modelfiles/production/ and its hash is logged daily. Rollback procedures are documented.",
    "controlObjective": "Ensure only ratified Modelfile versions are deployed to production inference.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-DAI-004",
    "processArea": "Data Governance and AI Integrity",
    "processName": "Corpus Ingestion Validation",
    "description": "dex-ingest.py runs a multi-stage validation pipeline before writing to ChromaDB: file type whitelist check, SHA-256 deduplication against existing chunks, header format validation for governed documents, and malware scan via Windows Defender integration. Any file failing validation is moved to quarantine with a detailed log entry.",
    "controlObjective": "Prevent malformed, duplicate, or unauthorized files from entering the canonical corpus.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "DAILY",
    "keyControl": True,
  },
  {
    "controlId": "CO-DAI-005",
    "processArea": "Data Governance and AI Integrity",
    "processName": "Collection Authority Governance",
    "description": "A configuration file defines all active collections and their weights. The query router reads this file and enforces tier-based precedence as defined in ADR-CORPUS-001. Any change to weights or collections requires a ratified ADR and is logged in the change history. A weekly audit verifies that actual retrieval matches expected precedence.",
    "controlObjective": "Ensure retrieval weights and collection precedence comply with ratified ADR-CORPUS-001.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "WEEKLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-DAI-006",
    "processArea": "Data Governance and AI Integrity",
    "processName": "RAG Response Accuracy Sampling",
    "description": "A random 5% sample of dex-bridge.py queries and responses is logged to a separate review queue. The operator reviews the sample weekly, scoring each response as CORRECT, PARTIAL, or CONFABULATED. Results are logged to calibration-log.jsonl. A confabulation rate greater than 2% triggers a review of the active Modelfile and retrieval parameters.",
    "controlObjective": "Detect and remediate confabulation or low-confidence responses from Dex Jr.",
    "controlType": "DETECTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "WEEKLY",
    "keyControl": True,
  },
  {
    "controlId": "CO-DAI-007",
    "processArea": "Data Governance and AI Integrity",
    "processName": "Data Retention and Purging",
    "description": "A data governance standard defines retention periods by data classification. A quarterly purge script identifies chunks older than their retention period, archives them to cold storage, and removes them from active ChromaDB collections. The purge log is reviewed and approved by the operator before execution.",
    "controlObjective": "Ensure data is retained only as required by policy and purged in a governed manner.",
    "controlType": "DETECTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "QUARTERLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-DAI-008",
    "processArea": "Data Governance and AI Integrity",
    "processName": "External Source Authorization",
    "description": "All external sources must be nominated by a council seat and approved by majority vote before ingestion. Approved sources are added to an allowlist in dex-ingest.py. The nominated-by flag tags all ingested chunks with the approving seat ID. Quarterly review of external source performance determines whether to renew or remove.",
    "controlObjective": "Prevent ingestion of unauthorized or low-quality external content into high-weight collections.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "QUARTERLY",
    "keyControl": False,
  },
  {
    "controlId": "CO-DAI-009",
    "processArea": "Data Governance and AI Integrity",
    "processName": "Model Calibration and Regression Testing",
    "description": "A suite of 20 canonical test prompts covering CR triggers, confabulation gates, knowledge queries, and boundary conditions is executed after every Modelfile change. Results are compared against baseline expected outputs. Any deviation exceeding threshold blocks production deployment until resolved. Results are logged to calibration-results.jsonl.",
    "controlObjective": "Ensure model behavior remains consistent with governance requirements after updates.",
    "controlType": "PREVENTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "AD_HOC",
    "keyControl": True,
  },
  {
    "controlId": "CO-DAI-010",
    "processArea": "Data Governance and AI Integrity",
    "processName": "Privacy Impact Assessment",
    "description": "Before any personal data is ingested, a Privacy Impact Assessment is documented and approved by the operator. The PIA specifies data types, retention, access controls, and purpose. The dex_dave collection is isolated by the query router and never included in default or governance queries. An annual review verifies continued compliance.",
    "controlObjective": "Ensure ingestion of personal data complies with privacy policies and regulatory requirements.",
    "controlType": "PREVENTIVE",
    "controlNature": "MANUAL",
    "controlFrequency": "ANNUAL",
    "keyControl": True,
  },
  {
    "controlId": "CO-DAI-011",
    "processArea": "Data Governance and AI Integrity",
    "processName": "Versioned Corpus Snapshots",
    "description": "After every major ingestion, an automated snapshot is created: the entire ChromaDB folder is copied to a dated backup location. A manifest file records collection counts and a SHA-256 hash of the folder. Snapshots are retained indefinitely and are read-only.",
    "controlObjective": "Preserve a point-in-time, immutable record of the corpus at key milestones for future audit or rollback.",
    "controlType": "DETECTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "AD_HOC",
    "keyControl": False,
  },
  {
    "controlId": "CO-DAI-012",
    "processArea": "Data Governance and AI Integrity",
    "processName": "Corpus Metadata Completeness",
    "description": "A weekly validation script scans all collections for chunks missing required metadata fields. Missing fields are flagged in a report and quarantined if critical. The operator reviews the report and takes corrective action. Compliance rate is tracked over time.",
    "controlObjective": "Ensure all chunks in canonical collections have required metadata fields populated.",
    "controlType": "DETECTIVE",
    "controlNature": "AUTOMATED",
    "controlFrequency": "WEEKLY",
    "keyControl": False,
  },
]

print(f"Total controls: {len(controls)}")

# Preview first
payload = {
    "companyId": COMPANY_ID,
    "controls": controls,
    "mode": "preview"
}

data = json.dumps(payload).encode("utf-8")
req = urllib.request.Request(
    f"{BASE_URL}/api/import",
    data=data,
    headers={"Content-Type": "application/json"},
    method="POST"
)

with urllib.request.urlopen(req) as resp:
    result = json.loads(resp.read())

print(f"Preview — Valid: {result['valid']} | Invalid: {result['invalid']}")
if result.get("warnings"):
    print("WARNINGS:")
    for w in result["warnings"]:
        print(f"  {w}")

if result["invalid"] == 0:
    print("\nAll valid. Running execute...")
    payload["mode"] = "execute"
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"{BASE_URL}/api/import",
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST"
    )
    with urllib.request.urlopen(req) as resp:
        result = json.loads(resp.read())
    print(f"Created: {result['created']} | Updated: {result['updated']} | Skipped: {result['skipped']}")
else:
    print("\nFix warnings before executing.")
