
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

async function main() {
  const company = await prisma.company.findUnique({ where: { companyId: 'CO-DDL' } })
  if (!company) throw new Error('Company CO-DDL not found')

  const staff = [
    // ── ITGC Team (Archer Hawthorne 1001) ────────────────────────
    { auditorId: 'ITGC-MGR-001', auditorName: 'Priya Desai', role: 'MANAGER', certifications: 'CISA, PMP', specializations: 'ITGC fieldwork execution, access management, change management', bio: 'Priya Desai is an IT audit manager with 7 years of Big 4 experience leading ITGC audits for technology and financial services clients. She joined DDL to bridge the gap between technical controls and governance. Her strength lies in translating technical risks into actionable audit findings.', strengths: 'Leads ITGC testing with consistent methodology; collaborates with engineers to validate backup and security configurations; focuses on high-impact controls and avoids nitpicking low-risk gaps', weaknesses: 'Hesitates to approve deviations from standards even when flexibility is needed; can get lost in access review spreadsheets and change approval logs' },
    { auditorId: 'ITGC-SR-001', auditorName: 'Daniel Carter', role: 'SENIOR', certifications: 'CISA, CRISC', specializations: 'Access management, database security, incident response', bio: 'Daniel Carter is a cybersecurity and IT audit senior with a background in penetration testing at a global cybersecurity firm. He joined DDL to ensure studio infrastructure is secure from both external and internal threats. His expertise in access controls and incident response makes him the go-to for technical audit testing.', strengths: 'Runs integrity checks and backup validations with a hacker mindset; develops scripts to validate backups and scan for API key leaks; leads incident response playbook development', weaknesses: 'Over-relies on automation sometimes missing manual review gaps; spends too much time validating edge cases' },
    { auditorId: 'ITGC-STF-001', auditorName: 'Sophie Nguyen', role: 'STAFF', certifications: 'CIA (in progress)', specializations: 'Access management reviews, change management testing, infrastructure security', bio: 'Sophie Nguyen is a governance and compliance analyst with IT audit experience at a mid-sized SaaS company. She joined DDL for hands-on ITGC and infrastructure security experience. Her role involves executing fieldwork including access reviews and change approvals.', strengths: 'Catches missing MFA enforcement and unapproved deployments; explains technical controls clearly to non-technical stakeholders; proactively flags potential risks', weaknesses: 'Over-cautious about approving minor deviations; struggles to prioritize tasks when multiple access reviews are pending' },
    { auditorId: 'ITGC-STF-002', auditorName: 'Ryan Patel', role: 'STAFF', certifications: 'CISSP (in progress)', specializations: 'Change management testing, infrastructure security assessments, access management reviews', bio: 'Ryan Patel is a compliance analyst with IT audit experience at a regional bank. He joined DDL to gain exposure to governance in a tech-driven environment. He brings a practical mindset focusing on what works rather than what is theoretically perfect.', strengths: 'Practical mindset focused on real-world context; uses metrics to identify systemic gaps; quickly learns new tools and applies them to testing', weaknesses: 'Struggles with gray areas in judgment calls; tends to over-document minor issues creating noise in review cycles' },

    // ── GOV Team (Marcus Caldwell 1002) ──────────────────────────
    { auditorId: 'GOV-MGR-001', auditorName: 'Nadia Okafor', role: 'MANAGER', certifications: 'CIA, PMP', specializations: 'Policy compliance monitoring, governance audit program management, remediation tracking', bio: 'Nadia Okafor spent six years managing governance audit programs at a regional bank before joining DDL. She runs day-to-day planning and supervision for Governance and Oversight engagements, translating structural frameworks into fieldwork plans. Her strength is turning abstract governance requirements into testable assertions.', strengths: 'Keeps engagements on timeline without sacrificing documentation quality; translates governance concepts into plain-language test steps; surfaces blockers early instead of absorbing them', weaknesses: 'Overly cautious about escalating findings to REVISE preferring one more piece of corroboration; occasionally over-manages staff workpapers instead of coaching' },
    { auditorId: 'GOV-SR-001', auditorName: 'Thomas Wyatt', role: 'SENIOR', certifications: 'CISA, CIA', specializations: 'Standards compliance testing, decision authority validation, document governance controls', bio: 'Thomas Wyatt leads fieldwork for Governance and Oversight owning the testing calendar and evidence collection workflow. He came from a Big Four IT audit practice specializing in policy gap assessments. He reads the standard, reads the system, and tells you where they diverge.', strengths: 'Meticulous evidence linkage tracing every finding to the specific standard clause it violates; catches version control gaps others walk past; reliable under volume with consistent quality', weaknesses: 'Writes findings at a technical depth requiring editing before client-facing delivery; prefers to receive the test plan rather than co-develop it' },
    { auditorId: 'GOV-STF-001', auditorName: 'Rachel Tseng', role: 'STAFF', certifications: 'CIA (candidate)', specializations: 'Protocol adherence testing, meeting governance documentation, approval workflow verification', bio: 'Rachel Tseng joined DDL from a master program in public administration with a concentration in organizational governance. She executes high-volume testing including protocol adherence walkthroughs, approval chain verification, and governance documentation completeness checks.', strengths: 'High-volume execution without error accumulation; asks precise clarifying questions that prevent rework downstream; picks up new test procedures quickly', weaknesses: 'Limited experience with ambiguous findings, tends to flag as exception rather than investigate root cause; still developing judgment on materiality thresholds' },
    { auditorId: 'GOV-STF-002', auditorName: 'Derek Langham', role: 'STAFF', certifications: 'CRMA (candidate)', specializations: 'Governance reporting accuracy, standards registry validation, cross-referencing policy to practice', bio: 'Derek Langham transferred into audit from DDL operations where he maintained internal documentation and configuration records. His operational background gives him an unusual advantage knowing what governance artifacts look like when actually used versus when they are shelf documents.', strengths: 'Spots discrepancies between documented governance and operational reality faster than anyone; strong at cross-referencing documents that should agree; reliable on repetitive testing', weaknesses: 'Writing is functional but flat, findings narratives need editing to convey significance; can be deferential to senior staff when his own observation contradicts them' },

    // ── FIN Team (Elias Mercer 1003) ─────────────────────────────
    { auditorId: 'FIN-MGR-001', auditorName: 'Lauren Whitaker', role: 'MANAGER', certifications: 'CPA, CFE', specializations: 'Revenue cycle walkthroughs, commission plan validation, cut-off testing', bio: 'Lauren spent eight years in public accounting leading revenue assurance engagements for SaaS and subscription companies before joining DDL. She excels at turning commission workflows into governed auditable flows and mentoring staff through complex ASC 606 scenarios.', strengths: 'Builds thorough walkthrough narratives that make preparers feel confident; catches mismatched recognition timing; keeps fieldwork on schedule when evidence is delayed', weaknesses: 'Occasionally pushes for more substantive testing than risk justifies extending hours; becomes visibly frustrated when preparer answers are vague' },
    { auditorId: 'FIN-SR-001', auditorName: 'Marcus Delgado', role: 'SENIOR', certifications: 'CPA, CISA', specializations: 'IT-dependent financial controls, automated revenue recognition, deferred revenue roll-forwards', bio: 'Marcus is a dual-certified CPA and CISA with experience auditing revenue systems at mid-sized SaaS firms. He leads control testing for DDL commission and revenue recognition automation, focusing on the intersection of IT general controls and financial statement assertions.', strengths: 'Translates technical system configurations into financial statement risk language; identifies control gaps in automated revenue schedules before financial close; produces clean organized workpapers', weaknesses: 'Over-relies on system-generated reports without enough corroborating evidence; slow to escalate issues when preparers provide incomplete responses' },
    { auditorId: 'FIN-STF-001', auditorName: 'Sarah Chen', role: 'STAFF', certifications: 'CPA (candidate)', specializations: 'Commission payment vouching, revenue cut-off sampling, deferred revenue analytical procedures', bio: 'Sarah joined DDL after two years in public accounting focused on technology clients. She executes detailed fieldwork for revenue and commission testing with a strong eye for documentation completeness and mathematical accuracy.', strengths: 'Extremely thorough in vouching every commission payment back to source contracts; organizes evidence packages so cleanly that seniors rarely need additional support; quickly masters new revenue recognition scenarios', weaknesses: 'Gets lost in details and needs prompting to step back; hesitant to push back on preparers when documentation is clearly insufficient' },
    { auditorId: 'FIN-STF-002', auditorName: 'Tyler Nguyen', role: 'STAFF', certifications: 'None', specializations: 'Revenue trend analysis, commission variance investigation, deferred revenue reconciliation', bio: 'Tyler is a recent accounting graduate who joined DDL after interning in financial reporting at a mid-sized SaaS company. He performs analytical procedures and supports commission testing with strong attention to trend anomalies and reconciliation details.', strengths: 'Spots unusual revenue or commission patterns through analytical review faster than most seniors; writes concise accurate variance explanations; extremely reliable with repetitive reconciliation tasks', weaknesses: 'Still developing confidence in challenging preparer explanations; can become overwhelmed when given too many concurrent testing areas' },

    // ── VND Team (Max Sullivan 1004) ──────────────────────────────
    { auditorId: 'VND-MGR-001', auditorName: 'Elena Vasquez', role: 'MANAGER', certifications: 'CISA, CISSP', specializations: 'Vendor due diligence, SLA monitoring, cloud cost governance, contract lifecycle management', bio: 'Elena Vasquez manages fieldwork execution for vendor audits with 8 years specializing in cloud provider risk at tech startups and mid-market SaaS firms. She previously led vendor governance for a dev shop migrating to multi-cloud, reducing vendor-related incidents by 70% through standardized onboarding checklists.', strengths: 'Converts dense vendor terms of service into one-page risk summaries; builds vendor dashboards that surface anomalies before billing spikes; excels at negotiating interim mitigations during incidents', weaknesses: 'Occasionally escalates minor SLA deviations to Director level unnecessarily; prefers Excel over AuditForge for vendor tracking during fieldwork' },
    { auditorId: 'VND-SR-001', auditorName: 'Raj Patel', role: 'SENIOR', certifications: 'CISM, CPA', specializations: 'Third-party risk assessments, API dependency mapping, GitHub dependency vulnerability management', bio: 'Raj Patel leads control testing with 5 years focused on third-party cyber risk and supply chain security from a Big Four technology risk practice. He developed automated dependency scanning for open-source libraries across 200 GitHub repos at a fintech SaaS provider.', strengths: 'Maps complex API dependencies to identify single points of failure; uses GitHub dependency graph to prioritize remediation by exploitability; documents vendor offboarding runbooks so cleanly they become client templates', weaknesses: 'Over-documents vendor access screenshots bloating workpapers; gets defensive when operators push back on temporary vendor access requests' },
    { auditorId: 'VND-STF-001', auditorName: 'Sophia Chen', role: 'STAFF', certifications: 'CISA', specializations: 'Vendor inventory maintenance, cloud billing analysis, vendor performance monitoring', bio: 'Sophia Chen executes vendor fieldwork with 2 years of experience testing SaaS vendor controls at regional audit firms. She specializes in reconciling multi-platform cloud billing against contractual commitments and flagging anomalous usage patterns early.', strengths: 'Spots billing anomalies across vendor platforms by pattern recognition alone; builds vendor performance scorecards that make SLA breaches immediately visible; validates vendor SOC reports against actual configs with surgical precision', weaknesses: 'Struggles to push back on vendor account reps during access requests; needs supervision when prioritizing findings across multiple vendors' },
    { auditorId: 'VND-STF-002', auditorName: "Liam O'Connor", role: 'STAFF', certifications: 'None', specializations: 'Vendor access testing, configuration drift analysis, API health monitoring', bio: "Liam O'Connor performs hands-on vendor testing fresh from rotational audit programs at boutique firms focused on technology risk. He excels at screenshot-driven evidence collection for vendor console configurations and validates API dependencies during vendor outages.", strengths: 'Collects comprehensive vendor console evidence packages faster than anyone on the team; builds simple API health check scripts that catch vendor regressions before production; never misses a dangling API key or unrevoked vendor role', weaknesses: 'Weak at interpreting vendor terms of service legalese without guidance; produces verbose workpaper comments that require Senior cleanup' },

    // ── HR Team (Rowan Bennett 1005) ──────────────────────────────
    { auditorId: 'HR-MGR-001', auditorName: 'Priya Nair', role: 'MANAGER', certifications: 'PHR, CIPP/US', specializations: 'Contractor onboarding and verification, access provisioning orchestration, training acknowledgement', bio: 'Priya has eight years of HR operations and compliance experience in SaaS and AI startups, running onboarding programs and managing identity verification vendors. She coordinates cross-functional provisioning with IT and legal and oversees day-to-day execution of workforce controls.', strengths: 'Efficient at operationalizing checklists into ticketed workflows; strong vendor management for identity verification; reliable at closing provisioning SLAs', weaknesses: 'Conservative about exceptions sometimes delaying urgent contractor starts; prefers structured processes which can frustrate highly autonomous contributors' },
    { auditorId: 'HR-SR-001', auditorName: 'Marcus Li', role: 'SENIOR', certifications: 'CISM, SHRM-SCP', specializations: 'Role catalog design, access recertification, offboarding and asset recovery', bio: 'Marcus is a senior HR auditor with experience designing role catalogs and conducting quarterly access recertifications for regulated environments. He leads control testing, performs recertification reviews, and manages offboarding audits to ensure assets and credentials are recovered.', strengths: 'Meticulous in evidence validation and recertification workflows; skilled at identifying orphaned access and remediation paths; effective coach for junior auditors', weaknesses: 'Focus on thoroughness can extend testing timelines; occasionally over-documents findings requiring manager prioritization' },
    { auditorId: 'HR-STF-001', auditorName: 'Elena Garcia', role: 'STAFF', certifications: 'HRBP Certificate', specializations: 'IP assignment verification, confidentiality agreement processing, training delivery tracking', bio: 'Elena is an HR compliance analyst with three years of experience supporting legal and HR teams in tech firms. She executes identity and agreement verification, maintains the personnel repository, and tracks training acknowledgements and renewals.', strengths: 'Fast and accurate at document verification and recordkeeping; good at following escalation rules and maintaining audit trails', weaknesses: 'Limited experience with complex legal disputes; requires senior guidance for edge-case contract language' },
    { auditorId: 'HR-STF-002', auditorName: 'Jonah Park', role: 'STAFF', certifications: 'CompTIA Security+', specializations: 'Background check coordination, access provisioning tickets, offboarding asset reconciliation', bio: 'Jonah is an operations-focused HR analyst who coordinates background screenings, manages provisioning tickets with IT, and executes offboarding checklists. He runs periodic access recertification reports and supports the manager in SLA tracking and exception handling.', strengths: 'Strong at operational follow-through and SLA monitoring; adept at reconciling asset inventories and producing clean evidence packages', weaknesses: 'Less experienced in policy design and escalation to legal; can be task-focused and may miss broader governance implications' },

    // ── COMM Team (Ava Sinclair 1006) ─────────────────────────────
    { auditorId: 'COMM-MGR-001', auditorName: 'Elena Vance', role: 'MANAGER', certifications: 'CCEP, PMP', specializations: 'Crisis communications planning, policy implementation, internal communications audits', bio: 'Elena is an experienced communications professional who transitioned into compliance and ethics after managing several high-stakes crisis response initiatives. She excels at translating high-level ethical principles into concrete testable control procedures. As Manager she is responsible for planning engagements and ensuring quality and timeliness of all fieldwork.', strengths: 'Exceptional at project management and breaking down complex audits into executable tasks; remains calm and methodical under pressure; builds strong rapport with control owners', weaknesses: 'Can be risk-averse sometimes over-scoping engagements to cover every edge case; may need encouragement to accept that some residual risk is acceptable' },
    { auditorId: 'COMM-SR-001', auditorName: 'Samuel Jones', role: 'SENIOR', certifications: 'CIPP/US', specializations: 'Digital advertising controls, social media governance, content verification workflows', bio: "Samuel's background is in digital marketing and ad operations with focus on compliance with privacy regulations and platform policies. As Senior he leads fieldwork for testing controls related to DDL web properties and external publications. He is skilled at tracing content from its source to its final public state.", strengths: 'Meticulous in tracing data flows and evidence chains; deep technical understanding of web and social media platforms; documents test procedures with clear reproducible steps', weaknesses: 'Tends to communicate in technical jargon that needs translation for non-technical stakeholders; sometimes focuses too heavily on the how of a control failure without escalating the why' },
    { auditorId: 'COMM-STF-001', auditorName: 'Chloe Kim', role: 'STAFF', certifications: 'CCEP (in progress)', specializations: 'Evidence gathering, brand asset verification, factual accuracy testing', bio: 'Chloe is a recent communications graduate with a keen interest in corporate ethics and technology. She is responsible for executing detailed test steps for controls related to public content, social media, and brand consistency. She is proficient at documenting test results and organizing evidence packages for review.', strengths: 'Highly organized and diligent with documentation; eager to learn and adept at quickly picking up new tools and processes; brings a fresh perspective on emerging social platforms', weaknesses: 'Lacks professional skepticism and may occasionally accept insufficient evidence without challenge; still developing confidence in interviewing senior control owners' },
    { auditorId: 'COMM-STF-002', auditorName: 'Ben Carter', role: 'STAFF', certifications: 'APR (in progress)', specializations: 'Meeting minute verification, internal policy review, stakeholder communication testing', bio: 'Ben has a background in journalism and is skilled at interviewing, note-taking, and synthesizing information. He executes tests that involve reviewing internal policies, verifying accuracy of meeting minutes against decisions made, and confirming stakeholder inquiries are handled according to protocol.', strengths: 'Excellent interviewing and listening skills; writes clear concise summaries of test findings; adept at identifying inconsistencies between documented procedures and observed practices', weaknesses: 'Can get lost in narrative details of a process sometimes requiring redirection to focus on the specific control objective; desire for a complete story can lead to over-testing non-key controls' },

    // ── OCM Team (Leo Prescott 1007) ──────────────────────────────
    { auditorId: 'OPS-MGR-001', auditorName: 'Julian Vance', role: 'MANAGER', certifications: 'CISA, ITIL 4', specializations: 'Change advisory operations, incident management, release governance', bio: "Julian manages operational fieldwork for DDL, translating Leo's architectural standards into actionable testing plans. Before joining DDL he spent six years in enterprise IT Service Management specializing in mapping the blast radius of unapproved system changes. He ensures every deployed artifact in the DDL ecosystem traces back to a ratified ADR.", strengths: 'Excellent at reconstructing the timeline of undocumented incidents; highly effective at managing cross-functional stakeholder interviews during fieldwork', weaknesses: 'Tends to over-engineer testing workpapers sometimes delaying the transition from Fieldwork to Reporting' },
    { auditorId: 'OPS-SR-001', auditorName: 'Clara Hayes', role: 'SENIOR', certifications: 'CIA', specializations: 'Version control auditing, rollback procedure testing, CI/CD pipeline governance', bio: 'Clara is the lead tester for Operations and Change Management. She is responsible for verifying the integrity of the CI/CD pipeline, specifically ensuring Vercel auto-deploys are governed by mandatory GitHub pull request approvals. She has a zero-tolerance policy for direct commits to the main branch.', strengths: 'Meticulous code repository analysis; quickly identifies bypassed approval workflows; writes highly concise and actionable control exceptions', weaknesses: 'Struggles with ambiguity when testing newly implemented iterative AI features where traditional SDLC controls are still maturing' },
    { auditorId: 'OPS-STF-001', auditorName: 'David Chen', role: 'STAFF', certifications: 'CompTIA Security+', specializations: 'Deployment log analysis, configuration management, ticket reconciliation', bio: 'David executes the bulk of substantive testing for change management controls. He specializes in reconciling ticket IDs against actual GitHub commit hashes to ensure every deployed change was formally requested, reviewed, and approved prior to production release.', strengths: 'Highly efficient at processing large volumes of deployment logs; strong scripting skills for automating evidence extraction', weaknesses: 'Occasionally misses the broader business context of a change focusing too heavily on mechanical matching of ticket IDs' },
    { auditorId: 'OPS-STF-002', auditorName: 'Maya Robinson', role: 'STAFF', certifications: 'CAPM', specializations: 'Emergency change protocol testing, business continuity plan reviews, post-mortem documentation', bio: 'Maya focuses on the exceptions to the rule, auditing how the studio handles emergency hot-fixes and system outages. She reviews incident post-mortems to verify that root causes were identified and that emergency access was revoked following remediation.', strengths: 'Excellent at interviewing operators during post-incident reviews; maintains a calm objective demeanor when discussing system failures', weaknesses: 'Needs more oversight when drafting management action plans; tends to suggest overly complex remediation steps for minor deviations' },

    // ── RI Team (Marcus Grey 1008) ────────────────────────────────
    { auditorId: 'RI-MGR-001', auditorName: 'Natalie Voss', role: 'MANAGER', certifications: 'CPA, CIA', specializations: 'Commission operations oversight, revenue-to-payout reconciliation, compensation policy interpretation', bio: 'Natalie Voss manages revenue integrity fieldwork with a background in controllership support and incentive compensation review for recurring-revenue businesses. She is experienced in tracing commission populations from billing records through final payout files and identifying where policy language fails to translate into executable rules.', strengths: 'Keeps fieldwork moving by translating policy language into reviewable test steps; spots mismatches between source revenue logic and payout outputs quickly; escalates ambiguous plan language early', weaknesses: 'Can default to manual review steps longer than necessary before trusting automation; sometimes over-relies on reconciliation evidence and underweights payout communication concerns' },
    { auditorId: 'RI-SR-001', auditorName: 'Daniel Mercer', role: 'SENIOR', certifications: 'CFE, CRMA', specializations: 'Commission calculation testing, exception analysis, dispute log review', bio: 'Daniel Mercer leads testing over commission calculations, overrides, and exception handling with a focus on whether payouts can be independently reproduced from approved rules. His prior work includes incentive compensation audits, payment exception investigations, and close-support analytics. He is particularly effective where manual adjustments create elevated error risk.', strengths: 'Recomputes complex payout scenarios cleanly and documents variance logic in a way reviewers can follow; identifies patterns in disputes and override behavior that point to weak upstream design; maintains strong evidence discipline when testing exception-heavy populations', weaknesses: 'Can become overly skeptical of undocumented business judgment slowing conclusion drafting; sometimes spends too much time perfecting sample support before moving to the next test area' },
    { auditorId: 'RI-STF-001', auditorName: 'Priya Holloway', role: 'STAFF', certifications: 'CIA', specializations: 'Payout tie-out testing, source data validation, workflow status verification', bio: 'Priya Holloway executes detailed fieldwork over payout populations, status workflows, and source-to-output consistency checks. Her experience is strongest in high-volume review environments where completeness, traceability, and record-level accuracy matter more than presentation polish.', strengths: 'Very strong at tracing record-level populations without losing count integrity; catches status workflow inconsistencies that others dismiss as minor process noise; produces organized support packages that reduce reviewer follow-up', weaknesses: 'Less comfortable making judgment calls when policy language is vague; can take longer on unusual exceptions because she prefers full support before concluding' },
    { auditorId: 'RI-STF-002', auditorName: 'Mason Ellery', role: 'STAFF', certifications: 'CPA', specializations: 'Revenue classification testing, period cutoff review, compensation statement validation', bio: 'Mason Ellery supports fieldwork focused on whether eligible revenue is classified correctly and paid in the correct period under the approved plan structure. He has practical experience reviewing close-cycle support, validating cutoff treatment, and comparing generated statements to source calculation files.', strengths: 'Strong at identifying where cutoff mistakes create downstream commission distortion; reads generated statements against source logic carefully enough to catch subtle mismatches; works well in structured testing programs with clear evidence standards', weaknesses: 'Can be rigid when the process requires pragmatic sequencing decisions under time pressure; sometimes underestimates how much narrative context reviewers need when explaining a clean exception pattern' },

    // ── DAI Team (Kai Langford 1009) ──────────────────────────────
    { auditorId: 'DGA-MGR-001', auditorName: 'Katherine Langford', role: 'MANAGER', certifications: 'CIA, CRMA', specializations: 'AI control framework design, data quality assurance methodologies, regulatory compliance for emerging technology', bio: 'Katherine has eight years of internal audit experience with the last four focused on technology and data governance. Before joining DDL she led data integrity audits at a regional bank and developed testing procedures for cloud migration projects. She brings a practitioner eye to abstract governance concepts.', strengths: 'Translates high-level Director guidance into concrete fieldwork plans; excellent at coaching staff through complex technical concepts; builds strong relationships with control owners facilitating smoother evidence collection', weaknesses: 'Hesitates to escalate problems to Director level until she has exhausted all options sometimes delaying course correction; tends to over-assign testing hours to junior staff rather than redistributing' },
    { auditorId: 'DGA-SR-001', auditorName: 'Marcus Keller', role: 'SENIOR', certifications: 'CISA, CDPSE', specializations: 'RAG system control testing, vector database access reviews, AI prompt governance validation', bio: 'Marcus came to audit after five years as a data engineer, giving him rare insight into how systems actually work not just how they are documented. He leads fieldwork on DDL most technically complex controls including those governing the RAG pipeline and vector store access.', strengths: 'Unusually skilled at designing test procedures for systems with no established audit precedent; catches control gaps during walkthroughs that others miss until testing phase; documents evidence in a way that tells a clear story not just a checklist', weaknesses: 'Impatient with manual testing steps sometimes seeks automation shortcuts before confirming the manual baseline works; can be dismissive of control owners who do not understand the technology they are responsible for' },
    { auditorId: 'DGA-STF-001', auditorName: 'Lena Cross', role: 'STAFF', certifications: 'CPA (in progress)', specializations: 'Data lineage tracing, metadata completeness validation, control documentation', bio: 'Lena joined DDL after two years in public accounting where she worked on financial statement audits and developed a reputation for meticulous workpaper documentation. She is now applying that discipline to data governance controls and quickly becoming the team expert on evidence organization.', strengths: 'Exceptional attention to detail and never misses a missing signature or incomplete evidence field; learns new control areas quickly and retains technical nuances; keeps the team organized tracking testing status without being asked', weaknesses: 'Reluctant to raise questions during fieldwork preferring to figure it out alone which sometimes leads to rework; can become hyper-focused on documentation formatting at the expense of testing progress' },
    { auditorId: 'DGA-STF-002', auditorName: 'Simon Blake', role: 'STAFF', certifications: 'DataCamp SQL and Python', specializations: 'SQL query validation, Python script testing, AI prompt review support', bio: 'Simon joined the team with a background in data analysis and a strong interest in AI governance. He supports the Senior on technical testing procedures and has quickly become proficient in validating SQL queries used in access reviews and testing automated controls.', strengths: 'Writes clear reproducible test scripts that can be reused across periods; asks good why questions that often uncover undocumented assumptions in control design; eager to take on challenging assignments and learns from feedback', weaknesses: 'Still developing professional skepticism and sometimes accepts control owner explanations without sufficient challenge; documentation is technically accurate but can be disorganized needing Senior review to structure findings clearly' },
  ]

  let created = 0
  let updated = 0

  for (const s of staff) {
    const existing = await prisma.auditor.findFirst({
      where: { companyId: company.id, auditorId: s.auditorId }
    })

    const data = {
      auditorId: s.auditorId,
      companyId: company.id,
      auditorName: s.auditorName,
      role: s.role,
      certifications: s.certifications,
      specializations: s.specializations,
      bio: s.bio,
      strengths: s.strengths,
      weaknesses: s.weaknesses,
      independence: 'INTERNAL',
      isActive: true,
    }

    if (existing) {
      await prisma.auditor.update({ where: { id: existing.id }, data })
      updated++
    } else {
      await prisma.auditor.create({ data })
      created++
    }
    console.log((existing ? 'Updated' : 'Created') + ': ' + s.auditorId + ' — ' + s.auditorName)
  }

  console.log('\nDone. Created: ' + created + ' | Updated: ' + updated)
  console.log('Total staff: ' + (created + updated))
}

main().catch(console.error).finally(() => prisma["$disconnect"]())
